config/routes.rb
Rails.application.routes.draw do

  resources :ppps

  resources :groups

  get 'comments/create'

  get 'home/index'

  resources :posts

  get 'tags/:tag', to: 'posts#index', as: :tag
  resources :tags

  root to: 'home#index'

  devise_for :users
  resources 'users' do
    member do
      get 'follow'
    end
  end

end

app/models/ppp.rb
class Ppp < ActiveRecord::Base
end

app/controllers/ppps_controller.rb
class PppsController < ApplicationController
  before_action :set_ppp, only: [:show, :edit, :update, :destroy]

  # GET /ppps
  # GET /ppps.json
  def index
    @ppps = Ppp.all
  end

  # GET /ppps/1
  # GET /ppps/1.json
  def show
  end

  # GET /ppps/new
  def new
    @ppp = Ppp.new
  end

  # GET /ppps/1/edit
  def edit
  end

  # POST /ppps
  # POST /ppps.json
  def create
    @ppp = Ppp.new(ppp_params)

    respond_to do |format|
      if @ppp.save
        format.html { redirect_to @ppp, notice: 'Ppp was successfully created.' }
        format.json { render :show, status: :created, location: @ppp }
      else
        format.html { render :new }
        format.json { render json: @ppp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ppps/1
  # PATCH/PUT /ppps/1.json
  def update
    respond_to do |format|
      if @ppp.update(ppp_params)
        format.html { redirect_to @ppp, notice: 'Ppp was successfully updated.' }
        format.json { render :show, status: :ok, location: @ppp }
      else
        format.html { render :edit }
        format.json { render json: @ppp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ppps/1
  # DELETE /ppps/1.json
  def destroy
    @ppp.destroy
    respond_to do |format|
      format.html { redirect_to ppps_url, notice: 'Ppp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ppp
      @ppp = Ppp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ppp_params
      params.require(:ppp).permit(:name)
    end
end

app/helpers/ppps_helper.rb
module PppsHelper
end

app/views/ppps/_form.html.erb
<%= form_for(@ppp) do |f| %>
  <% if @ppp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ppp.errors.count, "error") %> prohibited this ppp from being saved:</h2>

      <ul>
      <% @ppp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ppps/edit.html.erb
<h1>Editing ppp</h1>

<%= render 'form' %>

<%= link_to 'Show', @ppp %> |
<%= link_to 'Back', ppps_path %>

app/views/ppps/index.html.erb
<h1>Listing ppps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ppps.each do |ppp| %>
      <tr>
        <td><%= ppp.name %></td>
        <td><%= link_to 'Show', ppp %></td>
        <td><%= link_to 'Edit', edit_ppp_path(ppp) %></td>
        <td><%= link_to 'Destroy', ppp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ppp', new_ppp_path %>

app/views/ppps/new.html.erb
<h1>New ppp</h1>

<%= render 'form' %>

<%= link_to 'Back', ppps_path %>

app/views/ppps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ppp.name %>
</p>

<%= link_to 'Edit', edit_ppp_path(@ppp) %> |
<%= link_to 'Back', ppps_path %>