config/routes.rb
Rails.application.routes.draw do

  resources :ppps

  resources :groups

  get 'comments/create'

  get 'home/index'

  resources :posts

  get 'tags/:tag', to: 'posts#index', as: :tag
  resources :tags

  root to: 'home#index'

  devise_for :users
  resources 'users' do
    member do
      get 'follow'
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	include PublicActivity::Model
  tracked owner: ->(controller, model) { controller.current_user }
  
  belongs_to :user

  has_many :comments

  paginates_per 5

  has_many :taggings
  has_many :tags, through: :taggings

  def self.tagged_with(name)
  	Tag.find_by_name!(name).posts
  end

  def self.tag_counts
  	Tag.select("tags.*, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
  end

  def tag_list
  	tags.map(&:name).join(", ")
  end

  def tag_list=(names)
  	self.tags = names.split(",").map do |n|
  		Tag.where(name: n.strip).first_or_create!
  	end
  end

end

app/models/ppp.rb
class Ppp < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :posts, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  acts_as_followable
  acts_as_follower

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :user_groups
  has_many :groups, :through => :user_groups

end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	@post = Post.new
    @activities = PublicActivity::Activity.order("created_at desc").page(params[:page])
  end
  
end

app/controllers/ppps_controller.rb
class PppsController < ApplicationController
  before_action :set_ppp, only: [:show, :edit, :update, :destroy]

  # GET /ppps
  # GET /ppps.json
  def index
    @ppps = Ppp.all
  end

  # GET /ppps/1
  # GET /ppps/1.json
  def show
  end

  # GET /ppps/new
  def new
    @ppp = Ppp.new
  end

  # GET /ppps/1/edit
  def edit
  end

  # POST /ppps
  # POST /ppps.json
  def create
    @ppp = Ppp.new(ppp_params)

    respond_to do |format|
      if @ppp.save
        format.html { redirect_to @ppp, notice: 'Ppp was successfully created.' }
        format.json { render :show, status: :created, location: @ppp }
      else
        format.html { render :new }
        format.json { render json: @ppp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ppps/1
  # PATCH/PUT /ppps/1.json
  def update
    respond_to do |format|
      if @ppp.update(ppp_params)
        format.html { redirect_to @ppp, notice: 'Ppp was successfully updated.' }
        format.json { render :show, status: :ok, location: @ppp }
      else
        format.html { render :edit }
        format.json { render json: @ppp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ppps/1
  # DELETE /ppps/1.json
  def destroy
    @ppp.destroy
    respond_to do |format|
      format.html { redirect_to ppps_url, notice: 'Ppp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ppp
      @ppp = Ppp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ppp_params
      params.require(:ppp).permit(:name)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    render :text => "sdf"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def tag_cloud(tags, classes)
  	max = tags.sort_by(&:count).last
  	tags.each do |tag|
  	  index = tag.count.to_f / max.count * (classes.size - 1)
  	  yield(tag, classes[index.round])
  	end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/ppps_helper.rb
module PppsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ISad</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <ul class="nav navbar-nav">
    <li class="active"><a href="/">Home</a></li>
    <li><%= link_to "Posts", posts_path %></li>
    <li><%= link_to "Tags", tags_path %></li>
    <li><%= link_to "Users", users_path %></li>
    <li><%= link_to "Groups", groups_path %></li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
        <li><a href="#">Action</a></li>
        <li><a href="#">Another action</a></li>
        <li><a href="#">Something else here</a></li>
        <li class="divider"></li>
        <li class="dropdown-header">Nav header</li>
        <li><a href="#">Separated link</a></li>
        <li><a href="#">One more separated link</a></li>
      </ul>
    </li>
  </ul>


  <div class="container">
    <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>

        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse">
      <form class="navbar-form navbar-right" role="form">
        <div class="form-group">
          <input type="text" placeholder="Email" class="form-control">
        </div>
        <div class="form-group">
          <input type="password" placeholder="Password" class="form-control">
        </div>
        <button type="submit" class="btn btn-success">Sign in</button>
      </form>

    </div><!--/.navbar-collapse -->
  </div>
</div>


<%= yield %>

</body>
</html>